name: wdb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.3
  - numpy=2.2.5
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - selenium=4.31.0
  - beautifulsoup4=4.13.4
  - pytest=8.3.5
  - ipykernel=6.29.5
  - jupyter_client=8.6.3
  - pip
  - pip:
      - webdriver-manager==4.0.2
      - squarify==0.4.4
